version: '3.8'

services:
  app:
    build:
      context: ./backend
    ports:
      - "3005:3005" # App is exposed on port 3005
    depends_on:
      - db # Waits for the db container to start
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend:/app # Map local code to the container
      - /app/node_modules # Prevent overwriting node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enable polling mode for file watching
      CHOKIDAR_INTERVAL: 100 # Optional: Adjust polling interval in ms
    command: ["npm", "run", "start:dev"]
  db:
    image: mysql:8.0
    container_name: pocketdocs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pocketDocs
      MYSQL_USER: docuser1
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306" # MySQL is exposed on port 3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
