version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: pocketdocs-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: pocketDocs
      MYSQL_USER: docuser
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
